apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      volumes:
        - name: env-configmap
          configMap:
            name: env-config
      containers:
        - name: grpc-client-service
          image: grpc-load-balancing-k8s:latest
          imagePullPolicy: Never
          command: ["/app/grpc-lb", "client", "--numOfMsg", "3000"]
          volumeMounts:
            - name: env-configmap
              mountPath: /app/.env
              subPath: env
          resources:
            limits:
              cpu: 1000m
              memory: 1500Mi
            requests:
              cpu: 300m
              memory: 500Mi