apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  env: |-
    GRPC_SERVER_ADDRESS: 0.0.0.0:8080
    GRPC_CLIENT_ADDRESS: grpc-server-service-clusterip.default.svc.cluster.local:8080
