apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  env: |-
    GRPC_SERVER_PORT: 8080
    GRPC_SERVER_ADDRESS: 0.0.0.0:8080

    GRPC_CLIENT_PORT: 8081
    GRPC_CLIENT_ADDRESS: 0.0.0.0:8081

